# Generated by Django 2.2.2 on 2019-06-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_userprofile_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cpf',
        ),
    ]
