# Generated by Django 2.2.2 on 2019-06-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_remove_userprofile_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
